### ISSUE TITLE
Iroha python 1.4.1 - is code generated with too new version?

### ISSUE THREAD

**Issue by baziorek** [hyperledger/iroha-python#102]
Unfortunately I've prepared everything for new release: `iroha-python 1.4.1`. Unfortunately I noticed problems when importing some of python files generated from protobuf.

The problem which I noticed is:
```
/home/devops/.local/lib/python3.9/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.1.0) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/home/devops/watra-ledger/src/tokens/kezo.py", line 9, in <module>
    import iroha_common
  File "/home/devops/watra-ledger/src/iroha_common.py", line 7, in <module>
    from iroha import primitive_pb2, IrohaCrypto, binascii, IrohaGrpc, Iroha, commands_pb2, queries_pb2
  File "/home/devops/.local/lib/python3.9/site-packages/iroha/__init__.py", line 7, in <module>
    from .iroha import *
  File "/home/devops/.local/lib/python3.9/site-packages/iroha/iroha.py", line 17, in <module>
    from . import endpoint_pb2
  File "/home/devops/.local/lib/python3.9/site-packages/iroha/endpoint_pb2.py", line 38, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/devops/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
Fortunately the problem is when somebody is using deeper features of library (not just `import iroha` but e.g. `from iroha import primitive_pb2`).
________________
**First question - who saw the problem? Is the problem in Your environment? Please describe me details?**
________________
If somebody has the problem please tell me in the issue. Fastest solution is to add `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` environment variable. And I would have to generate files from protobuf files with older version, but it will take time...

**Comment by baziorek** [comment]
The fix was merged in: https://github.com/hyperledger/iroha-python/pull/104, so the issue can be closed. I'm the one who created, so probably nobody would be angry when I close its:D.
