### ISSUE TITLE
Iroha 2: "Unhandled rejection: ParityScale"

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-python#108]
`LoNeWoLf` [reported an error](https://discord.com/channels/905194001349627914/905205848547155968/998452452120604672) in Discord:

```python
return self.cl.submit_all_with_metadata(tx, {})
```

```
Exception: Error: Unexpected transaction response;
status: 500 Internal Server Error;
response body: Unhandled rejection: ParityScale
```

It happens with a standard `docker-compose.yml`, as shown in the tutorial.

Last commit in Iroha-python: [`04c7980d6e`](https://github.com/hyperledger/iroha-python/commit/04c7980d6e41828617bab9d77bf1bcdf3cb4f6e7), `iroha2` branch.
Last commit in Iroha: [`91da336af2`](https://github.com/hyperledger/iroha/commit/91da336af28a309b1e18376e38bdf69002dac5a5), `iroha2` branch.

The code used here is the standard example file, [`test.py`](https://github.com/hyperledger/iroha-python/blob/iroha2/example/test.py). There's the copy to be sure:

<details>
    <summary>Code</summary>

```python
import iroha2
import json
from iroha2 import Client
from iroha2.data_model import domain
from iroha2.data_model.isi import *
from iroha2.data_model.domain import *
from iroha2.data_model.expression import *
from iroha2.data_model.events import FilterBox, pipeline
from iroha2.data_model import *
cfg = json.loads(open("./config.json").read())
cl = Client(cfg)
domain = NewDomain("iroha_python")
register = Register.identifiable(domain)
hash = cl.submit_isi(register)
filter = FilterBox.Pipeline(
    pipeline.EventFilter(
        entity_kind=pipeline.EntityKind.Transaction(),
        status_kind=pipeline.StatusKind.Committed(),
        hash=None,
    ))
listener = cl.listen(filter)
for event in listener:
    print(event)
    if event["Pipeline"]["status"] == "Committed" \
        and event["Pipeline"]["hash"] == hash:
        break
```
</details>

**Comment by baziorek** [comment]
I faced similar problem:
-----
I was trying to execute sample code of Iroha 2 (sample from documentation: https://hyperledger.github.io/iroha-2-docs/guide/python.html#_2-configuring-iroha-2 and https://hyperledger.github.io/iroha-2-docs/guide/python.html#_3-registering-a-domain):
```
import json
from iroha2 import Client
from iroha2.data_model.isi import *
from iroha2.data_model.domain import *
from iroha2.data_model.expression import *
from iroha2.data_model import *


cfg = json.loads(open("config.json").read())
cl = Client(cfg)

domain = Domain("looking_glass")
register = Register(Expression(Value(Identifiable(domain))))
hash = cl.submit_isi(register)
print(hash)
```
The error message:
```
python iroha2_nauka.py
[{'Register': {'object': {'Raw': {'Identifiable': {'Domain': {'id': {'name': 'looking_glass'}, 'logo': 'QmQqzMTavQgT4f4T5v6PWBp7XNKtoPmC9jvn12WPT3gkSE', 'accounts': {}, 'asset_definitions': {}, 'metadata': {}}}}}}}]
Traceback (most recent call last):
  File "/home/agh/Pulpit/blockchain/iroha_code/iroha2/iroha2_nauka.py", line 16, in <module>
    hash = cl.submit_isi(register)
  File "/home/agh/.local/lib/python3.10/site-packages/iroha2/__init__.py", line 41, in submit_isi
    return self.submit_tx([_Instruction(isi)])
  File "/home/agh/.local/lib/python3.10/site-packages/iroha2/__init__.py", line 38, in submit_tx
    return self.cl.submit_all_with_metadata(tx, {})
Exception: Error: Unexpected transaction response; status: 500 Internal Server Error; response body: Unhandled rejection: ParityScale
    0: Unexpected transaction response; status: 500 Internal Server Error; response body: Unhandled rejection: ParityScale
```
Logs from nodes:
```
iroha-iroha0-1  | 2022-07-25T11:39:47.637254Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:59432}: warp::filters::trace: processing request
iroha-iroha0-1  | 2022-07-25T11:39:47.637362Z ERROR request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:59432}: warp::filters::trace: unable to process request (internal error) status=500 error=Rejection([MethodNotAllowed, ParityScale])
iroha-iroha0-1  | 2022-07-25T11:39:47.637375Z ERROR warp::reject: unhandled custom rejection, returning 500 response: ParityScale
iroha-iroha0-1  | 2022-07-25T11:45:01.298455Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:43302}: warp::filters::trace: processing request
iroha-iroha0-1  | 2022-07-25T11:45:01.298543Z ERROR request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:43302}: warp::filters::trace: unable to process request (internal error) status=500 error=Rejection([MethodNotAllowed, ParityScale])
iroha-iroha0-1  | 2022-07-25T11:45:01.298555Z ERROR warp::reject: unhandled custom rejection, returning 500 response: ParityScale
iroha-iroha0-1  | 2022-07-25T11:49:20.269353Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:59146}: warp::filters::trace: processing request
iroha-iroha0-1  | 2022-07-25T11:49:20.269427Z ERROR request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:59146}: warp::filters::trace: unable to process request (internal error) status=500 error=Rejection([MethodNotAllowed, ParityScale])
iroha-iroha0-1  | 2022-07-25T11:49:20.269438Z ERROR warp::reject: unhandled custom rejection, returning 500 response: ParityScale
iroha-iroha0-1  | 2022-07-25T11:49:57.016977Z  INFO request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:57332}: warp::filters::trace: processing request
iroha-iroha0-1  | 2022-07-25T11:49:57.017052Z ERROR request{method=POST path=/transaction version=HTTP/1.1 remote.addr=172.19.0.1:57332}: warp::filters::trace: unable to process request (internal error) status=500 error=Rejection([MethodNotAllowed, ParityScale])
iroha-iroha0-1  | 2022-07-25T11:49:57.017065Z ERROR warp::reject: unhandled custom rejection, returning 500 response: ParityScale
```
Does anybody know how to fix the problem?

**Comment by mersalin** [comment]
anyone have any solution on this? I am also facing the same issue. Thanks.

**Comment by matisalimbene** [comment]
@mersalin  I started trying other compose files and starting the network with docker-compose.dev.yml did work.

docker-compose.yml and docker-compose.stable.yml failed with the ParityScale error for me.

**Comment by mersalin** [comment]
@matisalimbene Thank you very much, It worked.
